version: "3.9"
services:
  web:
    build: ./web/.
    image: registry-intl.eu-central-1.aliyuncs.com/invest-platform-default/web:${IMAGE_TAG}
  api:
    build: ./api/.
    image: registry-intl.eu-central-1.aliyuncs.com/invest-platform-default/api:${IMAGE_TAG}