version: "3.9"
services:
  web:
    build: ./web/.
    precise-data-307722
    image: eu.gcr.io/precise-data-307722/web:${IMAGE_TAG}
  api:
    build: ./api/.
    image: eu.gcr.io/precise-data-307722/api:${IMAGE_TAG}