---
  symbols: [
  
     EURUSD=X, USDCNY=X, BTC-USD,
     ^GDAXI, ^MDAXI, ^SDAXI, ^TECDAX, ^DJI, ^IXIC, ^NDX, ^NDXT, ^GSPC, ^N225, ^HSI, ^HSCE, ^VIX,
     GC=F, NQ=F, YM=F, ES=F,
     
     IQQ6.DE, IBB, L0CK.DE, 2B78.DE, IHI, ESPO, SMH,
     
     GOOG, AAPL, FB, AMZN, MSFT, BABA, NNND.F, B1C.F,
     
     ]